server:
  port: 8081
spring:
  application:
    name: userservice-provider
dubbo:
  application:
    name: user-service-provider
  # 指定注册中心的地址
  registry:
    # 注册协议 zookeeper
    protocol: zookeeper
    address: 148.70.3.235:2181
  # dubbo 的协议
  protocol:
    name: dubbo
    # 服务的端口
    port: 20080

  # 监控中心
  monitor:
    # 监控协议 register
    # 表示从注册中心发现监控中心地址，否则直连监控中心
    protocol: register

    #也可以直连监控中心 默认端口为7070
    #address: 148.70.3.235:7070

