server:
  port: 8082
spring:
  application:
    name: userservice-cunsumer
dubbo:
  application:
    name: user-service-cunsumer
  # 指定注册中心的地址
  registry:
    # 注册协议 zookeeper
    protocol: zookeeper
    address: 148.70.3.235:2181

  # 监控中心
  monitor:
    # 监控协议 register
    # 表示从注册中心发现监控中心地址，否则直连监控中心
    protocol: register

    #也可以直连监控中心 默认端口为7070
    #address: 148.70.3.235:7070

